### ISSUE TITLE
need change the value "Ukraine (with Crimea)" to "Ukraine"

### ISSUE THREAD

**Issue by bezdna** [taginfo/dockerized-taginfo#1]
https://github.com/taginfo/dockerized-taginfo/blob/85920db6a108fc018530a25cf41a74ba4d0790c2/import/geofabrik.yml#L4810

"Ukraine (with Crimea)" in OSM database not have this value and all overpass wizard not work.

example link from page https://taginfo.geofabrik.de/europe/ukraine/tags/building=shop: 
https://overpass-turbo.eu/?w=%22building%22%3D%22shop%22+in+Ukraine+%28with+Crimea%29&R

but work this:
https://overpass-turbo.eu/?w=%22building%22%3D%22shop%22+in+Ukraine

**Comment by ImreSamu** [comment]
Thank you for the feedback and apologies for the late reply.

If I understand correctly, the example geofabrik taginfo
https://taginfo.geofabrik.de/europe/ukraine/tags/building=shop
uses a different fork ( https://github.com/geofabrik/taginfo ) and not this one.
Because of that, this issue will not be automatically fixed there.
